# Generated by Django 4.0.4 on 2022-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='edition',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rarity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
