# Generated by Django 4.0.4 on 2022-05-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_postal_code_order_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
