# Generated by Django 4.0.4 on 2022-05-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Commander'), ('shipped', 'Envoyer')], default='ordered', max_length=20),
        ),
    ]
