# Generated by Django 4.0.4 on 2022-05-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Commander', 'Commander'), ('Envoyer', 'Envoyer')], default='Commander', max_length=20),
        ),
    ]
